openapi: 3.0.3
info:
  title: Music API
  version: '1.0'
  description: Music API
  contact:
    name: API Support
    email: apisupport@music.com.au
paths:
  /artist:
    get:
      summary: Get artists
      operationId: get-artists
      tags:
        - Artist
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create artist
      operationId: create-artist
      tags:
        - Artist
      requestBody:
        description: Artist request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artist'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
        '400':
          $ref: '#/components/responses/BadRequest'
  /album/{albumId}:
    get:
      summary: Get album
      operationId: get-album-by-id
      tags:
        - Album
      parameters:
        - $ref: '#/components/parameters/AlbumId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  parameters:
    AlbumId:
      description: Album Id
      in: path
      name: albumId
      required: true
      schema:
        type: string
        example: '12345'
  schemas:
    Album:
      description: Album
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 12345
        name:
          type: string
          example: 'Nevermind'
        genre:
          $ref: '#/components/schemas/Genre'
        releaseDate:
          type: string
          format: date
          description: The date the album was released
          example: '2021-06-23'
      required:
        - name
        - genre
    Artist:
      description: Artist
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 12345
        name:
          type: string
          example: Nirvana
        genre:
          $ref: '#/components/schemas/Genre'
        albums:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/Album'
      required:
        - name
        - genre
        - albums
    Genre:
      type: string
      description: Genre of music
      enum:
        - Country
        - Grunge
        - Pop
        - Rock
        - Jazz
        - Punk
    Error:
      type: string
      example: Bad Request
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              Error:
                $ref: '#/components/schemas/Error'